name: iosApp
options:
  bundleIdPrefix: demo
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    PRODUCT_NAME: iosApp
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    ENABLE_USER_SCRIPT_SANDBOXING: NO

targets:
  iosApp:
    type: application
    platform: iOS
    sources:
      - path: iosApp
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        INFOPLIST_FILE: iosApp/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: demo.visualllm
        CODE_SIGN_ENTITLEMENTS: ""
    dependencies:
      - framework: ../composeApp/build/XCFrameworks/debug/Shared.xcframework
        embed: true
        codeSign: true
    preBuildScripts:
      - name: Build XCFramework
        script: |
          cd "$SRCROOT/.."
          ./gradlew :composeApp:assembleXCFramework
        basedOnDependencyAnalysis: false
        showEnvVars: false